"""Crops unit sprites to their visible content.

Buildings are pinned to the grid by their anchor so they keep their full frame,
but units only ever appear inside icon boxes -- rendered at a fixed footprint
they end up as a small model in a large transparent square. Cropping makes them
fill their card. Anchors are updated so nothing else has to care.

    python tools/crop_units.py
"""

import json
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPRITES = os.path.join(ROOT, 'assets', 'sprites')
ALPHA_FLOOR = 8          # ignore the faint spread of the contact shadow
PAD = 4


def main():
    manifest_path = os.path.join(SPRITES, 'sprites.json')
    manifest = json.load(open(manifest_path))
    changed = 0

    for name, entry in manifest.items():
        if not name.startswith('u_'):
            continue
        path = os.path.join(ROOT, entry['file'])
        if not os.path.exists(path):
            continue
        im = Image.open(path).convert('RGBA')
        alpha = im.split()[3]
        box = alpha.point(lambda v: 255 if v > ALPHA_FLOOR else 0).getbbox()
        if not box:
            continue
        left = max(0, box[0] - PAD)
        top = max(0, box[1] - PAD)
        right = min(im.width, box[2] + PAD)
        bottom = min(im.height, box[3] + PAD)
        if (right - left, bottom - top) == im.size:
            continue
        im.crop((left, top, right, bottom)).save(path)
        entry['w'] = right - left
        entry['h'] = bottom - top
        entry['anchorX'] = round(entry['anchorX'] - left, 1)
        entry['anchorY'] = round(entry['anchorY'] - top, 1)
        changed += 1

    json.dump(manifest, open(manifest_path, 'w'), indent=1, sort_keys=True)
    body = json.dumps(manifest, indent=1, sort_keys=True).replace('\n', '\n  ')
    with open(os.path.join(ROOT, 'js', 'sprites-manifest.js'), 'w') as fh:
        fh.write('/* Generated by tools/render_sprites.py -- do not edit by hand. */\n')
        fh.write('(function (G) {\n  G.SPRITES = ' + body + ';\n})(window.G = window.G || {});\n')
    print('cropped %d unit sprites' % changed)


if __name__ == '__main__':
    main()
