"""Record where the art actually is inside each sprite image.

Tapping a building on the village board resolves to a grid tile, which means
working out how far above its own footprint a sprite is drawn. The obvious
answer -- the distance from the top of the image to the anchor -- is wrong,
because a rendered sprite is a model inside a square frame with a lot of empty
sky above it. Over-estimating that height makes a squat building claim taps
several tiles away, and the wrong sheet opens.

This measures the opaque bounding box of every sprite and stores it as
`ink: [left, top, right, bottom]` in image pixels. The board uses it for hit
testing; nothing else has to change, and no sprite has to be re-rendered.

    python tools/ink_bounds.py
"""

import json
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPRITES = os.path.join(ROOT, 'assets', 'sprites')
ALPHA_FLOOR = 24        # below this a pixel is the outline's soft edge, not art


def main():
    manifest_path = os.path.join(SPRITES, 'sprites.json')
    manifest = json.load(open(manifest_path))
    done = skipped = 0

    for name, entry in sorted(manifest.items()):
        if entry.get('anim'):
            continue                    # atlases carry their own per-clip rects
        path = os.path.join(ROOT, entry['file'])
        if not os.path.exists(path):
            skipped += 1
            continue
        im = Image.open(path)
        if im.mode != 'RGBA':
            im = im.convert('RGBA')
        alpha = im.getchannel('A').point(lambda v: 255 if v >= ALPHA_FLOOR else 0)
        box = alpha.getbbox()
        if not box:
            skipped += 1
            continue
        # Stored against the published size, which is what the board draws at.
        sx = entry.get('w', im.width) / float(im.width)
        sy = entry.get('h', im.height) / float(im.height)
        entry['ink'] = [round(box[0] * sx, 1), round(box[1] * sy, 1),
                        round(box[2] * sx, 1), round(box[3] * sy, 1)]
        done += 1

    json.dump(manifest, open(manifest_path, 'w'), indent=1, sort_keys=True)
    body = json.dumps(manifest, indent=1, sort_keys=True).replace('\n', '\n  ')
    with open(os.path.join(ROOT, 'js', 'sprites-manifest.js'), 'w') as fh:
        fh.write('/* Generated by tools/render_sprites.py -- do not edit by hand. */\n')
        fh.write('(function (G) {\n  G.SPRITES = ' + body + ';\n})(window.G = window.G || {});\n')
    print('measured %d sprites, skipped %d' % (done, skipped))


if __name__ == '__main__':
    main()
