"""Drops manifest entries whose PNG is no longer on disk.

The renderer merges into the existing manifest so partial re-renders are cheap,
which means renames (or a change of naming scheme) can leave entries pointing at
files that were deleted. Run this after a re-render to clear them out.

    python tools/prune_manifest.py
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPRITES = os.path.join(ROOT, 'assets', 'sprites')


def main():
    manifest_path = os.path.join(SPRITES, 'sprites.json')
    manifest = json.load(open(manifest_path))

    kept, dropped = {}, []
    for name, entry in manifest.items():
        if os.path.exists(os.path.join(ROOT, entry['file'])):
            kept[name] = entry
        else:
            dropped.append(name)

    json.dump(kept, open(manifest_path, 'w'), indent=1, sort_keys=True)
    body = json.dumps(kept, indent=1, sort_keys=True).replace('\n', '\n  ')
    with open(os.path.join(ROOT, 'js', 'sprites-manifest.js'), 'w') as fh:
        fh.write('/* Generated by tools/render_sprites.py -- do not edit by hand. */\n')
        fh.write('(function (G) {\n  G.SPRITES = ' + body + ';\n})(window.G = window.G || {});\n')

    print('kept %d sprites, dropped %d stale entries' % (len(kept), len(dropped)))
    if dropped:
        print('  e.g. ' + ', '.join(sorted(dropped)[:6]))


if __name__ == '__main__':
    main()
